version: 2

sources:
  - name: raw                  
    database: neondb            
    schema: raw                 
    description: Strava raw tables

    tables:
      - name: strava_activities
        description: Raw Strava data from API
